### Health Check
GET http://localhost:3000/api/health

### Listar usuários
GET http://localhost:3000/api/users

### Criar usuário
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "nome" : "gisely",
  "email" : "gisely@outlook.com",
  "senha_hash" : "321"
}