### Health Check
GET http://localhost:3000/api/health

### Listar usuários
GET http://localhost:3000/api/users

### Criar usuário
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "nome" : "Ativin souza",
  "email" : "Ativin.souza@gmail.com",
  "password" : "12383746"
}

### BUSCAR USUÁRIO POR ID
GET http://localhost:3000/api/users/1


### ATUALIZAR UM USUÁRIO
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "nome" : "dwf",
  "email" : "htyh@outlook.com"
}

### EXCLUIR USUÁRIO
DELETE http://localhost:3000/api/users/5